### ISSUE TITLE
홈페이지 - 이달의 우수 파티장 / 추천 파티 리스트 / 국가 파티 리스트

### ISSUE THREAD

**Issue by A-Jamong** [FRONTENDSCHOOL10/hexagon-potatoes#133]
## 🧾 제목
홈페이지 - 이달의 우수 파티장 / 추천 파티 리스트 / 국가 파티 리스트 -> 상세 페이지로 이동하도록.

## ✅ TO-DO
- [ ] 이달의 우수 파티장 / 평점 임의로 넣어서 5에 해당하는 사람들만 몇개 뜨도록
- [ ] 추천 파티 리스트 / 평점 5에 해당하는 사람들이 모집중인 파티 띄워두기
- [ ] 국가 파티 리스트 / 해당 국가로 모집중인 파티 띄우기  

## 📎 참고
( ex. 만들 기능 스크린샷 )
