### ISSUE TITLE
코드 리팩토링 및 최종 수정

### ISSUE THREAD

**Issue by JubiJung** [FRONTENDSCHOOL10/hexagon-potatoes#175]
## 🧾 제목
코드 리팩토링 및 최종 수정

## ✅ TO-DO
- [ ] 접근성을 체크
- [ ] 페이지 성능 향상
- [ ] 에러 유발 코드 수정
- [ ] 중복 코드 정리

## 📎 참고
( ex. 만들 기능 스크린샷 )
