### ISSUE TITLE
input 컴포넌트 스타일링 및 기본 input 컴포넌트 추가

### ISSUE THREAD

**Issue by JubiJung** [FRONTENDSCHOOL10/hexagon-potatoes#42]
## 🧾 제목
article 컴포넌트 제작

## ✅ TO-DO
- [x] 기존 input 컴포넌트 스타일링
- [x] 기본 input 컴포넌트 제작
- [x] 로그인/회원가입/검색 input 에 x버튼 만들기

## 📎 참고
![Image](https://github.com/user-attachments/assets/0c800c01-95a8-4967-a04a-721f1e099a53)
![Image](https://github.com/user-attachments/assets/71d64921-15dd-48b8-a3fb-25ca63d70aa1)
![Image](https://github.com/user-attachments/assets/a2143e24-3c2b-415e-927d-902602ddf41e)
