### ISSUE TITLE
파티 상세 페이지 작업

### ISSUE THREAD

**Issue by JubiJung** [FRONTENDSCHOOL10/hexagon-potatoes#70]
## 🧾 제목
파티 상세 페이지 작업

## ✅ TO-DO
- [x] 파티 상세 페이지 마크업
- [x] 파티 상세 페이지 스타일링
- [x] 해당 페이지에 필요한 기능 정리 및 구현

## 📎 참고
![image](https://github.com/user-attachments/assets/c7e7d0f4-26a7-405f-b977-27047c65cd79)
