### ISSUE TITLE
주문 상세 페이지 제작

### ISSUE THREAD

**Issue by JubiJung** [FRONTENDSCHOOL10/hexagon-potatoes#78]
## 🧾 제목
주문 상세 페이지 제작

## ✅ TO-DO
- [x] 주문 상세 페이지 마크업 및 스타일링
- [ ] input 항목 입력됐는지 검증 로직 필요
- [ ] 결제 버튼 클릭하면 결제페이지로 이동

## 📎 참고
![image](https://github.com/user-attachments/assets/58784920-4065-44c9-ae1f-04dc5bd520c9)
