### ISSUE TITLE
검색 관련 페이지 마크업, 스타일링

### ISSUE THREAD

**Issue by A-Jamong** [FRONTENDSCHOOL10/hexagon-potatoes#88]
## 🧾 제목
검색 관련 페이지 마크업, 스타일링

## ✅ TO-DO
- [ ] 검색 관련 페이지 마크업
- [ ] 검색 관련 페이지 스타일링
- [ ] 최근 검색어나 그 하위에 있는 건 일단 하드코딩

## 📎 참고
<img width="501" alt="스크린샷 2024-09-10 오전 1 24 38" src="https://github.com/user-attachments/assets/6b85f957-c490-4107-b2dd-26d8491b6fe6">
