### ISSUE TITLE
input 컴포넌트 기능 수정

### ISSUE THREAD

**Issue by JubiJung** [FRONTENDSCHOOL10/hexagon-potatoes#91]
## 🧾 제목
input 컴포넌트 기능 수정

## ✅ TO-DO
- [x] 각 input을 가져와서 부모 컴포넌트에서 사용했을 때 데이터에 접근가능하도록 연결
- [x] 부모 컴포넌트와 자식 컴포넌트 간 유효성 검사 함수 props 연결
- [x] 기본 input에 type props 추가해서 input의 타입별로 반환하는 element를 구분하기

## 📎 참고
![image](https://github.com/user-attachments/assets/746273df-f4cd-4336-9bbf-d2898dbe6a8a)
![image](https://github.com/user-attachments/assets/2a43c912-6f24-40f7-a7f8-76169c2a2173)
